## Error message: libpython3.5m.so.1.0
Detail info: error while loading shared libraries: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
I have file /usr/local/lib/libpython3.5m.so.1.0, 
### Error in shell script when you invoke python3
```sh
LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH;export LD_LIBRARY_PATH

```

### Error in python script 
Add the following line at the top of python script
```py
exec env LD_LIBRARY_PATH=/usr/local/lib:/usr/local/pgsql/lib/:/opt/VDC/jdk/jre/lib/amd64/server:/opt/VDC/tomcat/lib:/opt/ServerAdmin/lib:/opt/VDC/tomcat/lib /usr/lo
cal/bin/python3 -x "$0" "$@"
```

### Error in postgres when create python function
```
Add the following line in postgresql.conf and restart database.
    dynamic_library_path = '/usr/local/lib:$libdir'

```
